Fix CI build: Use xcodegen to generate Xcode project
- Replace manual Xcode project creation with xcodegen
- xcodegen automatically creates correct project structure
- Added xcpretty for better build output
- Added build verification step

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,349 +22,40 @@ jobs:
       with:
         xcode-version: latest-stable
 
-    - name: Create Xcode project
+    - name: Create Xcode project using xcodegen
       run: |
-        # Create a basic Xcode project structure
-        mkdir -p HelloWorld.xcodeproj
+        # Install xcodegen
+        brew install xcodegen
 
-        # Create project.pbxproj file
-        cat > HelloWorld.xcodeproj/project.pbxproj << 'EOF'
-        // !$*UTF8*$!
-        {
-          archiveVersion = 1;
-          classes = {
-          };
-          objectVersion = 56;
-          objects = {
-            /* Begin PBXBuildFile section */
-            1A000001 /* HelloWorldApp.swift in Sources */ = {isa = PBXBuildFile; fileRef = 1A000002 /* HelloWorldApp.swift */; };
-            1A000003 /* ContentView.swift in Sources */ = {isa = PBXBuildFile; fileRef = 1A000004 /* ContentView.swift */; };
-            /* End PBXBuildFile section */
-
-            /* Begin PBXFileReference section */
-            1A000005 /* HelloWorld.app */ = {isa = PBXFileReference; explicitFileType = wrapper.application; includeInIndex = 0; path = HelloWorld.app; sourceTree = BUILT_PRODUCTS_DIR; };
-            1A000002 /* HelloWorldApp.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = HelloWorldApp.swift; sourceTree = "<group>"; };
-            1A000004 /* ContentView.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = ContentView.swift; sourceTree = "<group>"; };
-            1A000006 /* Info.plist */ = {isa = PBXFileReference; lastKnownFileType = text.plist.xml; path = Info.plist; sourceTree = "<group>"; };
-            /* End PBXFileReference section */
-
-            /* Begin PBXFrameworksBuildPhase section */
-            1A000007 /* Frameworks */ = {
-              isa = PBXFrameworksBuildPhase;
-              buildActionMask = 2147483647;
-              files = (
-              );
-              runOnlyForDeploymentPostprocessing = 0;
-            };
-            /* End PBXFrameworksBuildPhase section */
-
-            /* Begin PBXGroup section */
-            1A000008 = {
-              isa = PBXGroup;
-              children = (
-                1A000009 /* HelloWorld */,
-                1A00000A /* Products */,
-              );
-              sourceTree = "<group>";
-            };
-            1A000009 /* HelloWorld */ = {
-              isa = PBXGroup;
-              children = (
-                1A000002 /* HelloWorldApp.swift */,
-                1A000004 /* ContentView.swift */,
-                1A000006 /* Info.plist */,
-              );
-              path = HelloWorld;
-              sourceTree = "<group>";
-            };
-            1A00000A /* Products */ = {
-              isa = PBXGroup;
-              children = (
-                1A000005 /* HelloWorld.app */,
-              );
-              name = Products;
-              sourceTree = "<group>";
-            };
-            /* End PBXGroup section */
-
-            /* Begin PBXNativeTarget section */
-            1A00000B /* HelloWorld */ = {
-              isa = PBXNativeTarget;
-              buildConfigurationList = 1A00000C /* Build configuration list for PBXNativeTarget "HelloWorld" */;
-              buildPhases = (
-                1A00000D /* Sources */,
-                1A000007 /* Frameworks */,
-                1A00000E /* Resources */,
-              );
-              buildRules = (
-              );
-              dependencies = (
-              );
-              name = HelloWorld;
-              productName = HelloWorld;
-              productReference = 1A000005 /* HelloWorld.app */;
-              productType = "com.apple.product-type.application";
-            };
-            /* End PBXNativeTarget section */
-
-            /* Begin PBXProject section */
-            1A00000F /* Project object */ = {
-              isa = PBXProject;
-              attributes = {
-                BuildIndependentTargetsInParallel = 1;
-                LastSwiftUpdateCheck = 1500;
-                LastUpgradeCheck = 1500;
-                TargetAttributes = {
-                  1A00000B = {
-                    CreatedOnToolsVersion = 15.0;
-                  };
-                };
-              };
-              buildConfigurationList = 1A000010 /* Build configuration list for PBXProject "HelloWorld" */;
-              compatibilityVersion = "Xcode 14.0";
-              developmentRegion = en;
-              hasScannedForEncodings = 0;
-              knownRegions = (
-                en,
-                Base,
-              );
-              mainGroup = 1A000008;
-              productRefGroup = 1A00000A /* Products */;
-              projectDirPath = "";
-              projectRoot = "";
-              targets = (
-                1A00000B /* HelloWorld */,
-              );
-            };
-            /* End PBXProject section */
-
-            /* Begin PBXResourcesBuildPhase section */
-            1A00000E /* Resources */ = {
-              isa = PBXResourcesBuildPhase;
-              buildActionMask = 2147483647;
-              files = (
-              );
-              runOnlyForDeploymentPostprocessing = 0;
-            };
-            /* End PBXResourcesBuildPhase section */
-
-            /* Begin PBXSourcesBuildPhase section */
-            1A00000D /* Sources */ = {
-              isa = PBXSourcesBuildPhase;
-              buildActionMask = 2147483647;
-              files = (
-                1A000003 /* ContentView.swift in Sources */,
-                1A000001 /* HelloWorldApp.swift in Sources */,
-              );
-              runOnlyForDeploymentPostprocessing = 0;
-            };
-            /* End PBXSourcesBuildPhase section */
-
-            /* Begin XCBuildConfiguration section */
-            1A000011 /* Debug */ = {
-              isa = XCBuildConfiguration;
-              buildSettings = {
-                ALWAYS_SEARCH_USER_PATHS = NO;
-                ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS = YES;
-                CLANG_ANALYZER_NONNULL = YES;
-                CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION = YES_AGGRESSIVE;
-                CLANG_CXX_LANGUAGE_STANDARD = "gnu++20";
-                CLANG_ENABLE_MODULES = YES;
-                CLANG_ENABLE_OBJC_ARC = YES;
-                CLANG_ENABLE_OBJC_WEAK = YES;
-                CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES;
-                CLANG_WARN_BOOL_CONVERSION = YES;
-                CLANG_WARN_COMMA = YES;
-                CLANG_WARN_CONSTANT_CONVERSION = YES;
-                CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES;
-                CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR;
-                CLANG_WARN_DOCUMENTATION_COMMENTS = YES;
-                CLANG_WARN_EMPTY_BODY = YES;
-                CLANG_WARN_ENUM_CONVERSION = YES;
-                CLANG_WARN_INFINITE_RECURSION = YES;
-                CLANG_WARN_INT_CONVERSION = YES;
-                CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES;
-                CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES;
-                CLANG_WARN_OBJC_LITERAL_CONVERSION = YES;
-                CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR;
-                CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER = YES;
-                CLANG_WARN_RANGE_LOOP_ANALYSIS = YES;
-                CLANG_WARN_STRICT_PROTOTYPES = YES;
-                CLANG_WARN_SUSPICIOUS_MOVE = YES;
-                CLANG_WARN_UNGUARDED_AVAILABILITY = YES_AGGRESSIVE;
-                CLANG_WARN_UNREACHABLE_CODE = YES;
-                CLANG_WARN__DUPLICATE_METHOD_MATCH = YES;
-                COPY_PHASE_STRIP = NO;
-                DEBUG_INFORMATION_FORMAT = dwarf;
-                ENABLE_STRICT_OBJC_MSGSEND = YES;
-                ENABLE_TESTABILITY = YES;
-                ENABLE_USER_SCRIPT_SANDBOXING = YES;
-                GCC_C_LANGUAGE_STANDARD = gnu17;
-                GCC_DYNAMIC_NO_PIC = NO;
-                GCC_NO_COMMON_BLOCKS = YES;
-                GCC_OPTIMIZATION_LEVEL = 0;
-                GCC_PREPROCESSOR_DEFINITIONS = (
-                  "DEBUG=1",
-                  "$(inherited)",
-                );
-                GCC_WARN_64_TO_32_BIT_CONVERSION = YES;
-                GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR;
-                GCC_WARN_UNDECLARED_SELECTOR = YES;
-                GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE;
-                GCC_WARN_UNUSED_FUNCTION = YES;
-                GCC_WARN_UNUSED_VARIABLE = YES;
-                LOCALIZATION_PREFERS_STRING_CATALOGS = YES;
-                MACOSX_DEPLOYMENT_TARGET = 12.0;
-                MTL_ENABLE_DEBUG_INFO = INCLUDE_SOURCE;
-                MTL_FAST_MATH = YES;
-                ONLY_ACTIVE_ARCH = YES;
-                SDKROOT = macosx;
-                SWIFT_ACTIVE_COMPILATION_CONDITIONS = "DEBUG $(inherited)";
-                SWIFT_OPTIMIZATION_LEVEL = "-Onone";
-              };
-              name = Debug;
-            };
-            1A000012 /* Release */ = {
-              isa = XCBuildConfiguration;
-              buildSettings = {
-                ALWAYS_SEARCH_USER_PATHS = NO;
-                ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS = YES;
-                CLANG_ANALYZER_NONNULL = YES;
-                CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION = YES_AGGRESSIVE;
-                CLANG_CXX_LANGUAGE_STANDARD = "gnu++20";
-                CLANG_ENABLE_MODULES = YES;
-                CLANG_ENABLE_OBJC_ARC = YES;
-                CLANG_ENABLE_OBJC_WEAK = YES;
-                CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES;
-                CLANG_WARN_BOOL_CONVERSION = YES;
-                CLANG_WARN_COMMA = YES;
-                CLANG_WARN_CONSTANT_CONVERSION = YES;
-                CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES;
-                CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR;
-                CLANG_WARN_DOCUMENTATION_COMMENTS = YES;
-                CLANG_WARN_EMPTY_BODY = YES;
-                CLANG_WARN_ENUM_CONVERSION = YES;
-                CLANG_WARN_INFINITE_RECURSION = YES;
-                CLANG_WARN_INT_CONVERSION = YES;
-                CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES;
-                CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES;
-                CLANG_WARN_OBJC_LITERAL_CONVERSION = YES;
-                CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR;
-                CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER = YES;
-                CLANG_WARN_RANGE_LOOP_ANALYSIS = YES;
-                CLANG_WARN_STRICT_PROTOTYPES = YES;
-                CLANG_WARN_SUSPICIOUS_MOVE = YES;
-                CLANG_WARN_UNGUARDED_AVAILABILITY = YES_AGGRESSIVE;
-                CLANG_WARN_UNREACHABLE_CODE = YES;
-                CLANG_WARN__DUPLICATE_METHOD_MATCH = YES;
-                COPY_PHASE_STRIP = NO;
-                DEBUG_INFORMATION_FORMAT = "dwarf-with-dsym";
-                ENABLE_NS_ASSERTIONS = NO;
-                ENABLE_STRICT_OBJC_MSGSEND = YES;
-                ENABLE_USER_SCRIPT_SANDBOXING = YES;
-                GCC_C_LANGUAGE_STANDARD = gnu17;
-                GCC_NO_COMMON_BLOCKS = YES;
-                GCC_WARN_64_TO_32_BIT_CONVERSION = YES;
-                GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR;
-                GCC_WARN_UNDECLARED_SELECTOR = YES;
-                GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE;
-                GCC_WARN_UNUSED_FUNCTION = YES;
-                GCC_WARN_UNUSED_VARIABLE = YES;
-                LOCALIZATION_PREFERS_STRING_CATALOGS = YES;
-                MACOSX_DEPLOYMENT_TARGET = 12.0;
-                MTL_ENABLE_DEBUG_INFO = NO;
-                MTL_FAST_MATH = YES;
-                SDKROOT = macosx;
-                SWIFT_COMPILATION_MODE = wholemodule;
-              };
-              name = Release;
-            };
-            1A000013 /* Debug */ = {
-              isa = XCBuildConfiguration;
-              buildSettings = {
-                ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
-                ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME = AccentColor;
-                CODE_SIGN_ENTITLEMENTS = "";
-                CODE_SIGN_IDENTITY = "-";
-                CODE_SIGN_STYLE = Automatic;
-                COMBINE_HIDPI_IMAGES = YES;
-                CURRENT_PROJECT_VERSION = 1;
-                DEVELOPMENT_TEAM = "";
-                ENABLE_HARDENED_RUNTIME = YES;
-                ENABLE_PREVIEWS = YES;
-                GENERATE_INFOPLIST_FILE = NO;
-                INFOPLIST_FILE = HelloWorld/Info.plist;
-                INFOPLIST_KEY_NSHumanReadableCopyright = "";
-                INFOPLIST_KEY_NSMainStoryboardFile = "";
-                INFOPLIST_KEY_NSPrincipalClass = NSApplication;
-                LD_RUNPATH_SEARCH_PATHS = (
-                  "$(inherited)",
-                  "@executable_path/../Frameworks",
-                );
-                MARKETING_VERSION = 1.0;
-                PRODUCT_BUNDLE_IDENTIFIER = com.example.HelloWorld;
-                PRODUCT_NAME = "$(TARGET_NAME)";
-                SWIFT_EMIT_LOC_STRINGS = YES;
-                SWIFT_VERSION = 5.0;
-              };
-              name = Debug;
-            };
-            1A000014 /* Release */ = {
-              isa = XCBuildConfiguration;
-              buildSettings = {
-                ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
-                ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME = AccentColor;
-                CODE_SIGN_ENTITLEMENTS = "";
-                CODE_SIGN_IDENTITY = "-";
-                CODE_SIGN_STYLE = Automatic;
-                COMBINE_HIDPI_IMAGES = YES;
-                CURRENT_PROJECT_VERSION = 1;
-                DEVELOPMENT_TEAM = "";
-                ENABLE_HARDENED_RUNTIME = YES;
-                ENABLE_PREVIEWS = YES;
-                GENERATE_INFOPLIST_FILE = NO;
-                INFOPLIST_FILE = HelloWorld/Info.plist;
-                INFOPLIST_KEY_NSHumanReadableCopyright = "";
-                INFOPLIST_KEY_NSMainStoryboardFile = "";
-                INFOPLIST_KEY_NSPrincipalClass = NSApplication;
-                LD_RUNPATH_SEARCH_PATHS = (
-                  "$(inherited)",
-                  "@executable_path/../Frameworks",
-                );
-                MARKETING_VERSION = 1.0;
-                PRODUCT_BUNDLE_IDENTIFIER = com.example.HelloWorld;
-                PRODUCT_NAME = "$(TARGET_NAME)";
-                SWIFT_EMIT_LOC_STRINGS = YES;
-                SWIFT_VERSION = 5.0;
-              };
-              name = Release;
-            };
-            /* End XCBuildConfiguration section */
-
-            /* Begin XCConfigurationList section */
-            1A00000C /* Build configuration list for PBXNativeTarget "HelloWorld" */ = {
-              isa = XCConfigurationList;
-              buildConfigurations = (
-                1A000013 /* Debug */,
-                1A000014 /* Release */,
-              );
-              defaultConfigurationIsVisible = 0;
-              defaultConfigurationName = Release;
-            };
-            1A000010 /* Build configuration list for PBXProject "HelloWorld" */ = {
-              isa = XCConfigurationList;
-              buildConfigurations = (
-                1A000011 /* Debug */,
-                1A000012 /* Release */,
-              );
-              defaultConfigurationIsVisible = 0;
-              defaultConfigurationName = Release;
-            };
-            /* End XCConfigurationList section */
-          };
-          rootObject = 1A00000F /* Project object */;
-        }
+        # Create project.yml for xcodegen
+        cat > project.yml << 'EOF'
+        name: HelloWorld
+        options:
+          bundleIdPrefix: com.example
+          deploymentTarget:
+            macOS: "12.0"
+        targets:
+          HelloWorld:
+            type: application
+            platform: macOS
+            sources:
+              - HelloWorld
+            settings:
+              PRODUCT_BUNDLE_IDENTIFIER: com.example.HelloWorld
+              INFOPLIST_FILE: HelloWorld/Info.plist
+              MARKETING_VERSION: "1.0"
+              CURRENT_PROJECT_VERSION: "1"
+              CODE_SIGN_IDENTITY: "-"
+              CODE_SIGNING_REQUIRED: NO
+              CODE_SIGNING_ALLOWED: NO
+              ENABLE_HARDENED_RUNTIME: YES
+              COMBINE_HIDPI_IMAGES: YES
+              SWIFT_VERSION: "5.0"
+              MACOSX_DEPLOYMENT_TARGET: "12.0"
         EOF
+
+        # Generate Xcode project
+        xcodegen generate
 
     - name: Build app
       run: |
@@ -374,7 +65,14 @@ jobs:
           -derivedDataPath build \
           CODE_SIGN_IDENTITY="-" \
           CODE_SIGNING_REQUIRED=NO \
-          CODE_SIGNING_ALLOWED=NO
+          CODE_SIGNING_ALLOWED=NO \
+          | xcpretty || true
+
+        # Check if build succeeded
+        if [ ! -d "build/Build/Products/Release/HelloWorld.app" ]; then
+          echo "Build failed - app not found"
+          exit 1
+        fi
 
     - name: Create DMG
       run: |
@@ -410,5 +108,8 @@ jobs:
           ### System Requirements
           - macOS 12.0 (Monterey) or later
           - Apple Silicon or Intel Mac
+
+          ### Note
+          On first launch, you may need to right-click the app and select "Open" to bypass macOS Gatekeeper, as this app is not code-signed.
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
